#!/usr/bin/fish

# gets the command right as the pipe is run, so that it is most likely the correct command
set last_command (history | head -n 1)

# allows all the stdin to flow right passed tell me
while read -l line
    echo $line
end

telegram_tellme.py "$last_command finished"
